#!/bin/bash
MASTER=k3s-master
ssh -i ~/.ssh/proxmox-1 ubuntu@$MASTER 'sudo cat /etc/rancher/k3s/k3s.yaml' | sed -e 's/127.0.0.1/k3s-master/' > ~/.kube/k3s-config                                                         


