# see https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

kube-prometheus-stack:
  grafana:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: traefik
      # annotations:
      #   cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - grafana.example.com
      # tls:
      #   - secretName: grafana-tls
      #     hosts:
      #       - grafana.example.com
  alertmanager:
    enabled: true
  prometheus:
    enabled: true
    prometheusSpec:
      ingress:
        enabled: true
        ingressClassName: traefik
        # annotations:
        #   cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - prometheus.example.com
        paths:
          - /
        # tls:
        #   - secretName: prometheus-tls
        #     hosts:
        #       - prometheus.example.com
